FROM python:3.6

LABEL maintainer="sunita <sunitathakur1280@gmail.com>"

RUN mkdir -p /app
WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]

